databases:
  - name: Recipe_app
    ipAllowList: []

services:
  - type: web
    name: Recipe_app
    env: ruby # The version is automatically picked up from a .ruby-version file
    buildCommand: "./bin/render-build" # The script we just created above will run this to build our service
    startCommand: "./bin/rails server" # This gets called after build
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: events
          property: connectionString 